- docs/status/index.md
EIDF Service Status badges in both colour and text formatting are controlled via a second repository until we get actual live status endpoints. the status for each service (until we get endpoints to hit for live updates) would be stored in a JSON file in a repo (served on github.io) separately from the main docs - in the docs, we have a link to the shield.io service which takes in the file from the second repo and returns the badge image for up/down. To update the status, you would update the JSON file in the second repo rather than change the actual docs 
epcced/eidf-status repository with files in Data/ for all active/proposed services having a JSON file of format:
```json
{
"schemaVersion": 1,
"label": "",
"message": "Active Beta",
"color": "green"
}
```
Files in second repo:
- …
> AG: updated for status badges - using a third party badge generator

- docs/services/cs2/run.md
The link to SAFE does not work with `www` in it.
> Fix link to SAFE

- docs/services/gpuservice/index.md
- docs/services/gpuservice/policies.md
- mkdocs.yml
Addition and linking of GPU Service Policies Page with current information and update on TTL policy.
Informs users that a TTL will be applied to Kubernetes Jobs automatically.
mkdocs.yml
docs/services/gpuservice/index.md
docs/services/gpuservice/policies.md
> AG: updated to include page for service policies

- docs/services/gpuservice/faq.md
Add a solution of increasing SHM size.
It is useful to run single-node multi-gpus training.
The solution is about mounting an empty dir to /dev/shm.
The default shm size is 64M. It is too limited, so I met "sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 28] No space left on device." when I train a model with single-node multi-gpus.
There is no additional dependency.
Page: docs\services\gpuservice\faq.md
Section: Insufficient Shared Memory Size
> the solution for insufficient shared memory size

- Brewfile
- docs/access/ssh.md
Updated the SSH docs page to tell users to use Powershell os a WSL Linux Terminal to SSH into EIDF.
This was done as lots of users were having issues with Moba so it's easier for them to use WSL/Powershell like Mac/Linux users.
docs/access/ssh.md
> Remove MobaXTerm from Windows Docs

- docs/services/gpuservice/faq.md
Identified issue in Pytorch and OMP threads. OMP thread count should be manually set rather than relying on autodetection.
Added this to the FAQ.
GPU Service - FAQ
Pre-existing failure in pre-commit on ultra2 doc page.
> AG: added OMP Thread issue on Pytorch

- docs/services/cs2/run.md
Updating instructions to reflect that `python3.8` is found in `/usr/bin` rather than `/opt/python3.8/bin`.
Correctness of path.
> Update invocation of python3.8 on SDF

- docs/access/ssh.md
Added instructions to the SSH page on how to setup MFA through the portal for SSH-Gateway access once the Key + MFA settings are applied.
MERGE ON 18th JAN
Please delete options that are not relevant. 
eidf-docs/access/ssh/
/docs/access/ssh.md
> MFA instructions for SSH Gateway

- docs/access/virtualmachines-vdi.md
Remove ref to Guac Drag and Drop as that's not supported in EIDF
> Remove reference to Drag and Drop in Guacamole

- docs/services/gpuservice/faq.md
- docs/services/gpuservice/index.md
Updates text in GPU Service Overview and FAQ in response to user queries:
- Rewrote the service access section to try to highlight that it is the kubeconfig files that allows any VM within a project to access the service
- Separated description of quota and job queueing by creating a new entry in the Project Queue section
- New example use of kubectl in Overview page that explicitly uses -n flag
- Adds new section in FAQ giving an example forbidden error and the solution using the -n flag when using kubectl 
- Fixes #136 
- [ x ] Missing Documentation
Added new section to GPU Service FAQ:
- Access to GPU Service resources in default namespace is 'Forbidden'
Rewrote sections in GPU Service Overview for clarity:
- Service Access
- Project Quotas
- Project Queues
- [ x ] Documentation …
> Addresses namespace issue with kubectl usage

- docs/services/gpuservice/training/L1_getting_started.md
Adds a requirements section to the top of the lesson to emphasise the need to download the kubeconfig file to a VM and to take note of the namespace.
Justifies the wrapping of pods into jobs to allow the use of kueue early on.
Separates the creation of the first job yaml (with explanation) from the submission of the first job.
Adds a section explaining how to update the kubeconfig file so you do not need to use the -n flag every time.
- [ x ] Incomplete Documentation
gpuservice/training/L1_getting_started.md
- [ x ] Documentation follows the project style guidelines
- [ x ] Ensure Contact details contain Service Emails and Numbers
- [ x ] Self-review of documentation using mkdocs on local system
- [ x ] Spellcheck has been performed
- [ x ] …
> Refine job-only gpuservice lesson 1

- docs/access/ssh.md
- docs/access/virtualmachines-vdi.md
> Update ssh and vdi instructions with updated password guidance.

- mkdocs.yml
Minor changes to make it easier to view the docs built locally
1. Change `dev_addr` to `localhost` instead of `0.0.0.0` as the latter will not open now on latest browsers due to security issue on the use of `0.0.0.0` (e.g. https://www.theregister.com/2024/08/09/0000_day_bug/)
`mkdocs.yml`
> Minor fix to local build config

- docs/access/index.md
- docs/services/experimental/index.md
Add new docs for gateway.epcc.ed.ac.uk to clear up how to create accounts for non-EIDF users of the gateway service
https://safe.epcc.ed.ac.uk/TransitionServlet/Query/2569285
https://safe.epcc.ed.ac.uk/TransitionServlet/Query/2569246
https://safe.epcc.ed.ac.uk/TransitionServlet/Query/2565064
URL: /eidf-docs/services/experimental/
file: Docs/services/experimental/index.md
> Add docs for gateway.epcc.ed.ac.uk

- mkdocs.yml
Images were not showing after the migration of the old URL to docs.eidf.ac.uk.
Have removed "/eidf/docs" from the image URLs.
Updated site in mkdocs to reflect new URL and enable consistent checks with prod
Fixes #181 
> Update links after migration to docs.eidf.ac.uk

- docs/services/s3/tutorial.md
Include fix to turn off integrity protection for boto3. This was a breaking change in boto3 1.36.0 and is not supported by Ceph S3.
docs/services/s3/tutorial.md
> Update S3 docs: include fix for integrity protection that is not supported by Ceph S3

- docs/safe-haven-services/tre-container-user-guide/using-containers-in-the-tre.md
Adds a warning to instruct users not to call `docker` or `podman` commands directly.
As per the `Files changed` tab.
> TRE: add warning regarding usage of container CLIs

- docs/safe-haven-services/safe-haven-access.md
- docs/safe-haven-services/tre-container-user-guide/container-examples.md
Changed the TRE containers user guide `container-examples.md` file as discussed with Kostas and the team and the image links in the `safe-haven-access.md` document, which had an incorrect path. 
safe-haven-services/tre-container-user-guide/container-examples.md
safe-haven-services/safe-haven-access.md
> Updated TRE container examples and SH access links

- docs/services/s3/tutorial.md
Fix for S3 AWS CLI boto 1.36 default integrity protection
> Fix for S3 AWS CLI boto 1.36 default integrity protection

- docs/services/cerebras/run.md
Have added a simple toy vision model classification tutorial for training a vision transformer on a small subset of the Imagenet dataset using Cerebras 
> Add simple imagenet vision classification model tutorial

- docs/safe-haven-services/tre-container-user-guide/development-workflow.md
- docs/safe-haven-services/tre-container-user-guide/workflow-examples.md
I fixed the following failures in docs/safe-haven-services/tre-container-user-guide/workflow-examples.md:
```text
docs/safe-haven-services/tre-container-user-guide/workflow-examples.md:27: MD013 Line length
docs/safe-haven-services/tre-container-user-guide/workflow-examples.md:211: MD022 Headers should be surrounded by blank lines
docs/safe-haven-services/tre-container-user-guide/workflow-examples.md:375: MD031 Fenced code blocks should be surrounded by blank lines
docs/safe-haven-services/tre-container-user-guide/workflow-examples.md:474: MD032 Lists should be surrounded by blank lines
docs/safe-haven-services/tre-container-user-guide/workflow-examples.md:4: MD034 Bare URL used
docs/safe-haven-services/tre-container-user-guide/workflow-examples.md:320: MD034 Bare URL used …
```
> Fix 'pre-commit run --all-files' check failures

- docs/safe-haven-services/open-ondemand/apps/batch-container-app.md
- docs/safe-haven-services/open-ondemand/apps/jupyter-app.md
- docs/safe-haven-services/open-ondemand/apps/rstudio-app.md
- docs/safe-haven-services/open-ondemand/getting-started.md
- docs/safe-haven-services/open-ondemand/jobs.md
Open OnDemand cluster names no longer include 'tenant' in their short-name
```
docs/safe-haven-services/open-ondemand/apps/batch-container-app.md
docs/safe-haven-services/open-ondemand/apps/jupyter-app.md
docs/safe-haven-services/open-ondemand/apps/rstudio-app.md
docs/safe-haven-services/open-ondemand/getting-started.md
docs/safe-haven-services/open-ondemand/jobs.md
```
> Open OnDemand cluster names no longer include 'tenant' in their short-name
