EPCCed/eidf-docs

.github/ISSUE_TEMPLATE/Content.yml, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .mdl_style.rb, .mdlrc, .pre-commit-config.yaml, LICENSE.txt, README.md, docs/index.md, docs/metadata.md
Updated templates for Issues and pull request with a checklist in the pull request - should give format for the future pull requests. 
Added pre-commit config and markdownlint configuration.
Updated existing pages based on lint.
=> Issue and Pull Request Template, Pre-Commit Setup

docs/index.md
Fixes #13 
- [X ] Incomplete Documentation
index.md
=> Add support email address, fixes #13

docs/status/index.md, mkdocs.yml
Add basic UP/DOWN status page, hand cranked.
Users don't know when something is up or down unless we tell them via email.
None.
N/A
- [X ] New Documentation
status/index.md
- [ X] Documentation follows the project style guidelines
- [X ] Ensure Contact details contain Service Emails and Numbers
=> New Status Page

.gitignore, docs/services/cs1/access.md, docs/services/cs1/run.md, docs/services/ultra2/access.md, docs/services/ultra2/run.md, mkdocs.yml
- [ x] New Documentation
- [x ] Documentation follows the project style guidelines
- [x ] Ensure Contact details contain Service Emails and Numbers
- [x ] Self-review of documentation using mkdocs on local system
- [x ] Spellcheck has been performed
- [x ] Pre-commit has been run and passed
=> WIP: Adding cs1/u2 documentation.

CONTRIBUTING.md, docs/services/virtualmachines/docs.md, docs/services/virtualmachines/quickstart.md, docs/services/virtualmachines/tutorial.md
EIDF portal documentation:
- how to login
- create VM, register machine
- create user account, map user account
=> EIDF portal

docs/access/virtualmachines-vdi.md
Removed a Dev Mark
DevMark Removal
Virtual Desktop Interface - Navigating the EIDF VDI (Should be empty)
- [ X] Documentation follows the project style guidelines
- [ X] Ensure Contact details contain Service Emails and Numbers
- [ X] Self-review of documentation using mkdocs on local system
- [ X] Spellcheck has been performed
- [ X] Pre-commit has been run and passed
=> AW: Remove DevMark

CONTRIBUTING.md, docs/access/project.md, docs/services/cs1/access.md, docs/services/cs1/run.md, docs/services/ultra2/access.md, docs/services/ultra2/run.md, docs/services/virtualmachines/docs.md
Fixes to address markdown formatting in documentation to adhere to common standards.
modified:   CONTRIBUTING.md
modified:   docs/access/project.md
modified:   docs/services/cs1/access.md
modified:   docs/services/cs1/run.md
modified:   docs/services/ultra2/access.md
modified:   docs/services/ultra2/run.md
modified:   docs/services/virtualmachines/docs.md
=> AG: fixed Markdown issues on various files

docs/access/workshops/workshops.md
Fix EIDF URL link in docs/access/workshops/workshops.md
=> JH: Fix EIDF URL link in docs/access/workshops/workshops.md

docs/access/virtualmachines-vdi.md
Added link to SAFE documentation.
docs/access/virtualmachines-vdi.md
=> link to SAFE documentation

docs/access/ssh.md, docs/services/virtualmachines/docs.md
=> updated quota documentation and small changes to gateway SSH

docs/access/ssh.md, docs/access/virtualmachines-vdi.md, docs/access/workshops/index.md, docs/services/cs1/index.md, docs/services/datacatalogue/index.md, docs/services/jhub/index.md, docs/services/rstudioserver/index.md, docs/services/ultra2/index.md, docs/services/virtualmachines/index.md, mkdocs.yml
Index.md added to directories to address 404 issues in #18.
Linter warnings fixed in markdown.
Fixes #18 
index pages in virtualmachines and other services.
=> Update lint jun09

docs/access/index.md, docs/access/project.md, docs/index.md, docs/known-issues/index.md, docs/overview/acknowledgements.md, docs/overview/index.md, docs/services/virtualmachines/quickstart.md, mkdocs.yml
Revised ToC to match public service catalogue pages but left directories in place. Hopefully no external URLs (eg, EdDASH workshops) should break.
General edits. Fixed a couple of 404 links.
- [ X] Formatting
- [X ] New Documentation
See commit logs.
- [X ] Documentation follows the project style guidelines
- [X ] Ensure Contact details contain Service Emails and Numbers
- [X ] Self-review of documentation using mkdocs on local system
- [X ] Spellcheck has been performed
- [? ] Pre-commit has been run and passed
=> Restructured ToC and general edits

docs/services/virtualmachines/docs.md
Changes to portal VM creation: all in one step
Section `docs/services/virtualmachines/docs.md`
=> Reflect changes in VM creation in the portal

docs/status/index.md
Information about maintenance sessions
`docs/status/index.md`
=> added maintenance schedule

docs/services/virtualmachines/docs.md
New documentation for adding/removing sudo permissions for a user on selected VMs.
Computing Services -> Virtual Desktops -> Managing VMs
`services/virtualmachines/docs/`
=> how to grant sudo permissions

docs/status/index.md
Service status for EIDF Portal. Renamed VM Platform on status page.
Status page
=> Portal status in status page

docs/status/index.md
Removal of Notes column from status page, incorporating brief notes into a two part badge.
Allow service/system owners to update the status and a brief note without needing a pull request on main docs.
Changes to JSON Files in https://github.com/EPCCed/eidf-status
- Update to label and message, addition of field. This allows the status and brief note to be encapsulated in the badge.
- docs/status/index.md
=> AG: updated status table with combined badge status and note

docs/access/project.md
EIDF portal can now be accessed from anywhere without UoE VPN.
docs/access/project.md
=> Remove VPN only info for portal

docs/index.md
Fixed link in index page.
docs/index.md
=> updated link to EIDF website

docs/access/virtualmachines-vdi.md, docs/faq/index.md, docs/services/virtualmachines/docs.md
Added instructions to log out/log in when new connections are added to the VDI because the OpenID Connect user info may need to be refreshed before new connections appear.
```
access/virtualmachines-vdi.md
services/virtualmachines/docs.md
faq/index.md
```
=> VDI new connections refresh (and FAQ)

docs/services/virtualmachines/docs.md
New paragraph to explain who has permissions to manage VMs and user accounts, and how grant these permissions in SAFE.
New: first section in `docs/services/virtualmachines/docs.md`
=> Portal - member permissions for project management

docs/bespoke/eddash/workshops.md
1. docs/bespoke/eddash/workshops.md
=> JH: add entry for N8 CIR workshop in docs/bespoke/eddash/workshops.md

docs/services/virtualmachines/quickstart.md
Fix link in Quickstart page
`docs/services/virtualmachines/quickstart.md`
=> correct links

docs/faq/index.md
=> Fixes #69 Adds in explanation about non-default keys 

docs/access/ssh.md, docs/safe-haven-services/network-access-controls.md, docs/safe-haven-services/overview.md, docs/safe-haven-services/safe-haven-access.md, docs/safe-haven-services/using-the-hpc-cluster.md, docs/safe-haven-services/virtual-desktop-connections.md, docs/services/virtualmachines/flavours.md, mkdocs.yml
=> Add VM Flavours Information

docs/services/virtualmachines/flavours.md, docs/services/virtualmachines/index.md, docs/services/virtualmachines/tutorial.md
Update to flavour table.
Delete unused files.
docs/services/virtualmachines/flavours.md
=> Update to flavour names and DRAM in GB

docs/access/ssh.md
=> Disambiguate ssername syntax

docs/faq/index.md
Point to query form in FAQ: how to contact the helpdesk
- [] Incomplete Documentation
docs/faq/index.md
=> Link to portal query form in FAQs

docs/faq/index.md, docs/services/virtualmachines/flavours.md
Point to support request form for project quota update/project extension.
* docs/faq/index.md
* docs/services/virtualmachines/flavours.md
=> FAQ: project extension

docs/access/index.md
Fix broken links
Fixes #83 
https://epcced.github.io/eidf-docs/access/
=> Fix a couple of rogue broken links.

docs/services/virtualmachines/policies.md, mkdocs.yml
Policy page for end of project in the DSC
New page `docs/services/virtualmachines/policies.md`
=> DSC policies

docs/services/gpuservice/training/L1_getting_started.md, docs/services/gpuservice/training/L2_requesting_persistent_volumes.md, docs/services/gpuservice/training/L3_running_a_pytorch_task.md
Changes documentation relating to the EIDFGPUS service.
Pod policy update requires all pods to have resource requests and limits for CPUs and memory.
This pull request adds a section about the new pod resource spec requirements and updates all the example pods so that they include limits and resquests.
- [ x ] Incomplete Documentation
- [ x ] Documentation follows the project style guidelines
- [ x ] Ensure Contact details contain Service Emails and Numbers
- [ x ] Self-review of documentation using mkdocs on local system
- [ x ] Spellcheck has been performed
- [ x ] Pre-commit has been run and passed
=> Added requests and limits to all pods

docs/services/gpuservice/policies.md
Addition of policy for ADS to GPU Service policy page.
Information for users of the GPU Service
docs/services/gpuservice/policies.md
=> AG: policy ADS update for GPU Service

docs/services/virtualmachines/policies.md
Fixes #85 
docs/services/virtualmachines/policies.md
=> Fixes issue #85

docs/services/virtualmachines/index.md, docs/services/virtualmachines/policies.md
Fix some minor formatting and syntax errors.
docs/services/virtualmachines/index.md
docs/services/virtualmachines/policies.md
=> Minor formatting

docs/services/gpuservice/faq.md, mkdocs.yml
Addition of a specific FAQ for GPU Service. This will expand to include specific issues encountered via user feedback and other problems or short term workarounds.
This will avoid filling the main FAQ with GPU Service information.
services/gpuservice/faq.md
=> AG: added specific FAQ to the GPU Service

docs/services/cs2/run.md, docs/services/ultra2/run.md
TOTP now enabled for SDf-CS1 / Ultra2 users, but this is not reflected in the docs.
Fixes #114 
ultra2/run.md
cs2/run.md
=> Reflect changes to the login process for U2/CS-2

docs/services/graphcore/faq.md, docs/services/graphcore/index.md, docs/services/graphcore/training/L1_getting_started.md, docs/services/graphcore/training/L2_multiple_IPU.md, docs/services/graphcore/training/L3_profiling.md, docs/services/graphcore/training/L4_other_frameworks.md, docs/services/index.md, mkdocs.yml
Added documentation for Graphcore service. 
Sections to be added:
- graphcore/index.md : Service Access and Project Quotas sections
graphcore/index.md
graphcore/faq.md
graphcore/training/L1_getting_started.md
graphcore/training/L2_multiple_IPU.md
graphcore/training/L3_profiling.md
graphcore/training/L4_other_frameworks.md
=> JL: added graphcore service documentation

docs/services/graphcore/index.md, docs/services/graphcore/training/L1_getting_started.md
Added link to service access via GPU.
Added summary that no quota mechanism is in place for IPUJobs.
Fixed Graphcore name in a few places.
Graphcore Index
Note: failure on MD046 on ultra2/run.md pre-existing not in scope for this pull request.
=> AG: updates for draft for access and lack of quota

docs/services/graphcore/training/L1_getting_started.md, docs/services/graphcore/training/L2_multiple_IPU.md, docs/services/graphcore/training/L3_profiling.md, docs/services/graphcore/training/L4_other_frameworks.md
Changes to Job YAML Files examples to include generateName and resources/limits to fit with cluster environment and multi-user in the same namespace.
Graphcore Tutorial L1-L4.
=> AG: update to job definitions to avoid name clashes and pod limits

docs/services/gpuservice/faq.md, docs/services/gpuservice/training/L1_getting_started.md, docs/services/graphcore/training/L1_getting_started.md
generateName indent fix in initial example jobs for Graphcore and GPU Service.
Graphcore and GPU L1 Initial Tutorials.
=> AG: indent fix for initial example jobs

docs/services/cs2/run.md
Change CS2 "run" docs to reflect it now being a cluster and using appliance mode.
docs/services/cs2/run.md
=> WIP: Update to reflect change to WSC

docs/services/gpuservice/training/L5_devspace.md, mkdocs.yml
Address devspace formating and add link to lesson to sidebar
https://github.com/DimmestP/eidf-docs/blob/feat_gpu_devspace_guide/docs/services/gpuservice/training/L5_devspace.md
=> Address devspace formating and add link to lesson to sidebar

docs/services/cs2/run.md, docs/services/ultra2/run.md
Minor tweaks to CS2 docs.
docs/services/cs2/run.md
docs/services/ultra2/run.md
=> Minor update to CS2 WSC docs/Troubleshooting.

docs/services/virtualmachines/policies.md
Add VM patching policy to docs.
Fixes #134 
docs/service/virtualmachines/policies.md
=> Update VM policy statement to mention patching.

docs/services/gpuservice/training/L2_requesting_persistent_volumes.md, docs/services/gpuservice/training/L3_running_a_pytorch_task.md
Added a requirements section and kubectl -n <project-namespace> to align with lesson 1.
- [ x ] Incomplete Documentation
gpuservice/training/L2_requesting_persistent_volumes.md
gpuservice/training/L3_running_a_pytorch_task.md
- [ x ] Documentation follows the project style guidelines
- [ x ] Ensure Contact details contain Service Emails and Numbers
- [ x ] Self-review of documentation using mkdocs on local system
- [ x ] Spellcheck has been performed
- [ x ] Pre-commit has been run and passed
=> Add requirements and namespace to gpu l2 and l3

.pre-commit-config.yaml, docs/services/gpuservice/faq.md, docs/services/virtualmachines/index.md, mkdocs.yml
Minor typo changes and removal of links to upcoming service documentation.
Documentation Fixes Fixes #147 , #146,  #118
docs/services/gpuservice/faq.md
mkdocs.yml
docs/services/virtualmachines/index.md
=> Typo fixes

docs/services/cs2/run.md, docs/services/ultra2/access.md, docs/services/ultra2/connect.md, docs/services/ultra2/index.md, docs/services/ultra2/run.md, mkdocs.yml
Rationalize further Ultra2 documentation
docs/services/ultra2/{run,connect,access}.md
mkdocs.yml
=> Rationalisation of Ultra2 Documentation.

docs/services/cs2/run.md
Bump CS2 pytorch version to match firmware.
=> Bump CS2 software version.

docs/services/virtualmachines/policies.md
Automatic security updates in Rocky are now turned on for EIDF VMs.
=> Automatic security updates for Rocky

.gitignore, docs/safe-haven-services/tre-container-user-guide/advise-ig-required-software-stack.md, docs/safe-haven-services/tre-container-user-guide/building-and-testing-containers.md, docs/safe-haven-services/tre-container-user-guide/development-workflow.md, docs/safe-haven-services/tre-container-user-guide/introduction.md, docs/safe-haven-services/tre-container-user-guide/using-containers-in-the-tre.md, mkdocs.yml
This pull request adds basic documentation for using the Container Execution Service within the Trusted Research Environment safe havens. 
It adds a subsection under the existing "Safe Havens" section.
Fixes #160 
`docs/safe-haven-services/tre-container-user-guide`
=> TRE Documentation Section

docs/services/virtualmachines/docs.md
Reboot and update instructions for users.
`docs/services/virtualmachines/docs.md`
=> Add update instructions for VMs

docs/tutorial-videos/index.md, mkdocs.yml
A new page to the EIDF docs that is a list of links to Media hopper where the tutorial videos are hosted.
- [ x ] New Documentation
- [ x ] Documentation follows the project style guidelines
- [ x ] Ensure Contact details contain Service Emails and Numbers
- [ x ] Self-review of documentation using mkdocs on local system
- [ x ] Spellcheck has been performed
- [  ] Pre-commit has been run and passed
=> New EIDF Tutorial Video Index Page

docs/safe-haven-services/tre-container-user-guide/container-examples.md, docs/services/cs2/access.md
Removed names from TRE Container examples and replaced with reference to the standard EIDF contact address. Corrected a typo.
=> TRE container examples - minor edits

docs/status/index.md
=> add status panel to page

docs/services/cs2/run.md
This pull requests fixes a broken link in the documentation for Cerebras.
docs/services/cs2/run.md
=> fixed broken links in documentation for Cerebras CS-2

docs/safe-haven-services/safe-haven-access.md, docs/safe-haven-services/tre-container-user-guide/container-examples.md, docs/safe-haven-services/tre-container-user-guide/using-containers-in-the-tre.md, docs/safe-haven-services/virtual-desktop-connections.md
Fixed broken formatting in `container-examples.md`.
Fixed image formatting in `safe-haven-access.md` and `virtual-desktop-connections.md`.
Formatting in `container-examples.md`, `safe-haven-access.md` and `virtual-desktop-connections.md`.
=> Fixing formatting issues

docs/safe-haven-services/tre-container-user-guide/container-examples.md
Delete duplicated lines & fix a few typos.
See the files changed tab.
=> Update TRE CES Examples

docs/services/s3/tutorial.md
Added some information about Cyberduck to view S3 buckets. Also, put in 
a link to other programming language APIs. No dependencies are required.
No issues involved.
Just a paragraph and one line at the end of the Commands section.
=> Added information about Cyberduck.

docs/services/gpuservice/index.md, docs/services/gpuservice/kueue.md, docs/services/gpuservice/policies.md, docs/services/gpuservice/training/L1_getting_started.md, docs/services/gpuservice/training/L2_requesting_persistent_volumes.md, docs/services/gpuservice/training/L3_running_a_pytorch_task.md, docs/services/gpuservice/training/L4_template_workflow.md
Formatting, structural and content changes introduced with the cluster update of April 2025.
=> gpu documentation updates

docs/services/gpuservice/faq.md, docs/services/gpuservice/index.md, docs/services/gpuservice/policies.md, docs/services/gpuservice/training/L2_requesting_persistent_volumes.md
Summary of GPU Service spec has been updated on the GPU Service overview page. 
Minor wording change in L2 Tutorials - must to should.
FAQ update to include csi-cephfs-sc as a solution to the not mounting in multiple pods issue.
Minor whitespace updates.
FAQ Line 23-25
Overview line 10-30
=> AG: added updated cluster spec

docs/services/gpuservice/index.md
Simplification of GPU Descriptors on suggestion from Kostas.
Overview lines 4-6
=> Gpu summary update 2

docs/access/project.md, docs/services/datapublishing/catalogue.md, docs/services/datapublishing/service.md, docs/services/s3/tutorial.md
Update the description of the project application forms.
Add a paragraph to explain to users that project managers create accounts and they cannot request an account as they do for HPC projects in SAFE.
access/project.md
=> Update Portal application docs

docs/status/index.md
ACF outage alert on the status page.
=> ACF outage alert

docs/stylesheets/access.css, mkdocs.yml, overrides/main.html
Add  overrides folder and announcement block to main page.
=> Announcement block for ACF outage

docs/services/cerebras/connect.md, docs/services/cerebras/run.md
Update Cerebras docs to reference R2.5.0
- docs/services/cerebras/connect.md
- docs/services/cerebras/run.md
=> Update to R2.5.0

docs/storage/overview.md
Ultra2 cannot access CephFS shared filesystem
=> Shared storage table update

docs/services/virtualmachines/rdp-tunnelling.md, mkdocs.yml
docs/services/virtualmachines/rdp-tunnelling.md
=> Adding RDP tunnelling over SSH doc

docs/services/gitlab/quickstart.md, mkdocs.yml
docs/services/gitlab/quickstart.md
=> Add SSH keys part to Gitlab docs.
